USE [FileWorx]
GO

/****** Object:  Table [dbo].[T_BUSSINESSOBJECT]    Script Date: 5/8/2022 12:06:34 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_BUSSINESSOBJECT](
	[ID] [uniqueidentifier] NOT NULL,
	[C_DESCRIPTION] [nvarchar](255) NULL,
	[C_CREATIONDATE] [smalldatetime] NOT NULL,
	[C_NAME] [nvarchar](255) NOT NULL,
	[C_CLASSID] [int] NOT NULL,
 CONSTRAINT [PK_T_BUSSINESSOBJECT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

