USE [FileWorx]
GO

/****** Object:  Table [dbo].[T_FILE]    Script Date: 5/8/2022 12:08:02 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_FILE](
	[ID] [uniqueidentifier] NOT NULL,
	[C_BODY] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_T_FILE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[T_FILE]  WITH NOCHECK ADD  CONSTRAINT [FK_T_FILE_T_BUSSINESSOBJECT] FOREIGN KEY([ID])
REFERENCES [dbo].[T_BUSSINESSOBJECT] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
NOT FOR REPLICATION 
GO

ALTER TABLE [dbo].[T_FILE] CHECK CONSTRAINT [FK_T_FILE_T_BUSSINESSOBJECT]
GO

