USE [FileWorx]
GO

/****** Object:  Table [dbo].[T_NEWS]    Script Date: 5/8/2022 12:09:56 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_NEWS](
	[ID] [uniqueidentifier] NOT NULL,
	[C_CATEGORY] [int] NOT NULL,
 CONSTRAINT [PK_T_NEWS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[T_NEWS]  WITH CHECK ADD  CONSTRAINT [FK_T_NEWS_T_BUSSINESSOBJECT1] FOREIGN KEY([ID])
REFERENCES [dbo].[T_BUSSINESSOBJECT] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[T_NEWS] CHECK CONSTRAINT [FK_T_NEWS_T_BUSSINESSOBJECT1]
GO

