USE [FileWorx]
GO

/****** Object:  Table [dbo].[T_USER]    Script Date: 5/8/2022 12:09:10 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[T_USER](
	[ID] [uniqueidentifier] NOT NULL,
	[C_USERNAME] [nvarchar](255) NOT NULL,
	[C_PASSWORD] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK__USER__3214EC27D72F6A71] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[T_USER]  WITH CHECK ADD  CONSTRAINT [FK_USER_T_BUSSINESSOBJECT] FOREIGN KEY([ID])
REFERENCES [dbo].[T_BUSSINESSOBJECT] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[T_USER] CHECK CONSTRAINT [FK_USER_T_BUSSINESSOBJECT]
GO

